from .dd import BDD
from .fsm import BddFsm
from .prop import Spec
from typing import Union, Tuple, Literal

def check_ltl_spec(spec: Spec) -> bool: ...
def check_explain_ltl_spec(spec: Spec) -> Union[Tuple[Literal[True], None], Tuple[Literal[False], list[dict[str, str]]]]: ...
def eval_simple_expression(fsm: BddFsm, sexp: str) -> BDD: ...
