from .fsm import BddFsm
from typing import Iterator

propTypes: dict[str, int]

class Prop:
    type: int = ...
    expr: Spec = ...
    bddFsm: BddFsm = ...

class PropDb:
    master: Prop = ...
    def __iter__(self) -> Iterator[Prop]: ...

class Spec:
    type: int = ...
    car: Spec = ...
    cdr: Spec = ...
